### ISSUE TITLE
Thanks! But one question.

### ISSUE THREAD

**Issue by jonathanslenders** [jasontbradshaw/gapbuffer#1]
Thank you, very interesting approach to implement a gap buffer. I needed something similar, so it was very interesting to read through the code.

One question though, according to this page [0], the 'u' type for arrays will be removed in Python 4.0. Have you any idea why? Will we get an alternative?

Thanks,
Jonathan

[0] https://docs.python.org/dev/library/array.html

**Comment by jasontbradshaw** [comment]
Golly, I didn't know anyone ever looked at this!

That being said, unless I find an actual use for this library myself, I don't have any plans to update it to support Python 4.0. 

Pull requests are always welcome, of course!

**Comment by jonathanslenders** [comment]
Thanks, I was working on a Vi clone for Python: https://github.com/jonathanslenders/pyvim

I works really well, but it doesn't handle large files yet. So, if I find some time, I'll rewrite the data structures and the code around it to perform better. This was already a nice example. Cheers!

**Comment by jasontbradshaw** [comment]
Ha, I was going to do exactly the same project, which is what sparked this to begin with. I never got further than the base data structure though, clearly :)
